baseURL = "https://eatrunco.de"
languageCode = "en-us"
theme = "hugo-classic"

[[menu.main]]
    name = ""
    url = "/"
    weight = 1
[[menu.main]]
    name = "about"
    url = "/about/"
    weight = 2
